/**
 * Graphics Registry - Single Source of Truth
 *
 * This file re-exports the auto-generated graphics registry and provides
 * helper functions for querying and filtering graphics.
 *
 * The registry data is generated by scripts/buildGraphicsRegistry.js from
 * manifest files in stage/graphics/.
 *
 * Schema Reference:
 * {
 *   id: 'graphic-id',           // Unique identifier (must match button id)
 *   label: 'Display Name',      // Display name in UI
 *   labelTemplate: '{teamName} Display',  // Optional: dynamic substitution
 *   category: 'pre-meet',       // Category for grouping
 *   keywords: ['search', 'terms'],  // For smart recommendations
 *   gender: 'both',             // 'mens' | 'womens' | 'both'
 *   minTeams: 1,                // Optional: minimum teams required
 *   maxTeams: 7,                // Optional: maximum teams supported
 *   renderer: 'overlay',        // 'overlay' (overlays/*.html) | 'output' (output.html) | 'stage' (stage.html)
 *   file: 'filename.html',      // File path or graphic name (for overlay/output)
 *   skeleton: 'skeleton-name',  // Skeleton name (for stage renderer)
 *   blocks: ['block1', 'block2'], // Block names (for stage renderer)
 *   transparent: true,          // For OBS background handling
 *   perTeam: false,             // If true, generates team1-*, team2-*, etc.
 *   params: {                   // Parameter schema
 *     paramName: {
 *       type: 'string',         // string | number | enum | boolean
 *       source: 'competition',  // Auto-fill from competition config
 *       required: true,
 *       options: ['a', 'b'],    // For enum type
 *       default: 'a',           // Default value
 *       dependsOn: { otherParam: 'value' },  // Conditional visibility
 *     },
 *   },
 * }
 *
 * Categories (from categories.json):
 * - full-screen-cards: Leaderboards, team info, sponsors
 * - lower-thirds: Event info, team stats, spotlight
 * - full-bleed: Slates, stream, sponsors
 * - video-frames: Camera layouts, apparatus frames
 * - standalone: Logos, calendar, bugs
 * - event-summary: Rotation and apparatus summaries
 *
 * Parameter Sources:
 * - competition: Auto-filled from competition config (team logos, names, etc.)
 * - theme: Resolved from competition's theme config
 * - user: Requires user input (default if no source specified)
 * - computed: Calculated at runtime (e.g., sponsors list)
 */

// Import auto-generated registry data
import { GRAPHICS, CATEGORIES } from './graphicsRegistry.generated';

// Re-export for direct access
export { GRAPHICS, CATEGORIES };

// ============================================================
// HELPER FUNCTIONS
// ============================================================

/**
 * Get all graphics as a flat array
 * @returns {Array} Array of all graphic definitions
 */
export function getAllGraphics() {
  return Object.values(GRAPHICS);
}

/**
 * Get a single graphic by ID
 * @param {string} id - Graphic ID
 * @returns {Object|undefined} Graphic definition or undefined
 */
export function getGraphicById(id) {
  return GRAPHICS[id];
}

/**
 * Get graphics filtered by category
 * @param {string} category - Category name
 * @returns {Array} Array of graphic definitions in that category
 */
export function getGraphicsByCategory(category) {
  return getAllGraphics().filter(g => g.category === category);
}

/**
 * Get all unique categories
 * @returns {Array} Array of category names
 */
export function getCategories() {
  const categories = new Set(getAllGraphics().map(g => g.category));
  return Array.from(categories);
}

/**
 * Check if a graphic is available for a given competition type
 * @param {Object} graphic - Graphic definition
 * @param {string} compType - Competition type (e.g., 'womens-quad', 'mens-dual')
 * @param {number} teamCount - Number of teams
 * @returns {boolean} True if graphic is available
 */
export function isGraphicAvailable(graphic, compType, teamCount) {
  // Check gender filter
  const isMens = compType?.startsWith('mens');
  if (graphic.gender === 'mens' && !isMens) return false;
  if (graphic.gender === 'womens' && isMens) return false;

  // Check team count constraints
  if (graphic.minTeams && teamCount < graphic.minTeams) return false;
  if (graphic.maxTeams && teamCount > graphic.maxTeams) return false;

  return true;
}

/**
 * Get graphics available for a specific competition, with dynamic labels
 * @param {string} compType - Competition type (e.g., 'womens-quad', 'mens-dual')
 * @param {Object} teamNames - Team names keyed by number (e.g., { 1: 'UCLA', 2: 'Oregon' })
 * @param {string} [category] - Optional category filter
 * @returns {Array} Array of graphic definitions with resolved labels
 */
export function getGraphicsForCompetition(compType, teamNames = {}, category = null) {
  const isMens = compType?.startsWith('mens');
  const teamCount = Object.keys(teamNames).length || 2;

  const results = [];

  for (const graphic of getAllGraphics()) {
    // Filter by category if specified
    if (category && graphic.category !== category) continue;

    // Check availability
    if (!isGraphicAvailable(graphic, compType, teamCount)) continue;

    // Handle perTeam graphics - expand to team1-*, team2-*, etc.
    if (graphic.perTeam) {
      for (let i = 1; i <= teamCount; i++) {
        const teamName = teamNames[i] || `Team ${i}`;
        const expandedId = `team${i}-${graphic.id.replace('team-', '')}`;
        const label = graphic.labelTemplate
          ? graphic.labelTemplate.replace('{teamName}', teamName)
          : `${teamName} ${graphic.label.replace('Team ', '')}`;

        results.push({
          ...graphic,
          id: expandedId,
          label,
          team: i,
        });
      }
    } else {
      // Regular graphic - just add with optional label substitution
      let label = graphic.label;
      if (graphic.labelTemplate) {
        // Replace any team name placeholders
        for (const [num, name] of Object.entries(teamNames)) {
          label = label.replace(`{team${num}Name}`, name);
        }
      }
      results.push({ ...graphic, label });
    }
  }

  return results;
}

/**
 * Get recommended graphic based on segment name
 * @param {string} segmentName - Name of the segment (e.g., "UCLA Coaches Introduction")
 * @param {string} compType - Competition type
 * @param {Object} teamNames - Team names keyed by number
 * @returns {Object|null} Best matching graphic with confidence score, or null
 */
export function getRecommendedGraphic(segmentName, compType, teamNames = {}) {
  if (!segmentName) return null;

  const normalizedName = segmentName.toLowerCase();
  const availableGraphics = getGraphicsForCompetition(compType, teamNames);

  let bestMatch = null;
  let bestScore = 0;

  for (const graphic of availableGraphics) {
    let score = 0;

    // Check keywords
    for (const keyword of graphic.keywords || []) {
      if (normalizedName.includes(keyword.toLowerCase())) {
        score += 10;
      }
    }

    // Check label match
    if (normalizedName.includes(graphic.label.toLowerCase())) {
      score += 20;
    }

    // Check team name match for per-team graphics
    if (graphic.team) {
      const teamName = teamNames[graphic.team];
      if (teamName && normalizedName.includes(teamName.toLowerCase())) {
        score += 30;
      }
    }

    if (score > bestScore) {
      bestScore = score;
      bestMatch = graphic;
    }
  }

  if (bestMatch && bestScore > 0) {
    // Calculate confidence (0-1)
    const confidence = Math.min(1, bestScore / 50);
    return { ...bestMatch, confidence };
  }

  return null;
}

/**
 * Check if a graphic should have a transparent background
 * @param {string} graphicId - Graphic ID
 * @returns {boolean} True if transparent
 */
export function isTransparentGraphic(graphicId) {
  // Handle team-specific graphics
  if (/^team\d+-(stats|coaches)$/.test(graphicId)) {
    return true;
  }

  const graphic = getGraphicById(graphicId);
  return graphic?.transparent ?? false;
}

export default {
  GRAPHICS,
  CATEGORIES,
  getAllGraphics,
  getGraphicById,
  getGraphicsByCategory,
  getCategories,
  isGraphicAvailable,
  getGraphicsForCompetition,
  getRecommendedGraphic,
  isTransparentGraphic,
};
